CREATE TABLE IF NOT EXISTS signals (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    topic_id BIGINT NULL,
    external_id VARCHAR(100) NULL,
    symbol VARCHAR(30) NOT NULL,
    direction ENUM('BUY','SELL') NOT NULL,
    price DECIMAL(20,10) NULL,
    change_24h DECIMAL(10,4) NULL,
    rsi_14 DECIMAL(10,4) NULL,
    market_sentiment INT NULL,
    macd VARCHAR(100) NULL,
    open_interest_value DECIMAL(20,4) NULL,
    open_interest_raw VARCHAR(50) NULL,
    funding_rate DECIMAL(12,8) NULL,
    signal_score DECIMAL(10,4) NULL,
    btc_change_1h DECIMAL(20,8) NULL,
    sl_price DECIMAL(20,10) NULL,
    sl_percent DECIMAL(10,4) NULL,
    tp1_price DECIMAL(20,10) NULL,
    tp2_price DECIMAL(20,10) NULL,
    tp3_price DECIMAL(20,10) NULL,
    raw_text TEXT NULL,
    status ENUM('NEW','SKIPPED','APPROVED','ORDER_PLACED','POSITION_OPENED','CLOSED','FAILED') NOT NULL DEFAULT 'NEW',
    skip_reason VARCHAR(255) NULL,
    error_message TEXT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_source_external_id (external_id),
    KEY idx_symbol (symbol),
    KEY idx_direction (direction),
    KEY idx_status (status),
    KEY idx_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
