CREATE TABLE IF NOT EXISTS trades (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    signal_id BIGINT UNSIGNED NULL,
    symbol VARCHAR(32) NOT NULL,
    direction VARCHAR(8) NOT NULL,
    bingx_order_id VARCHAR(100) NULL,
    bingx_position_id VARCHAR(100) NULL,
    entry_price DECIMAL(30,12) NOT NULL,
    avg_entry_price DECIMAL(30,12) NULL,
    margin_usdt DECIMAL(30,12) NULL,
    leverage INT NOT NULL,
    volume DECIMAL(30,12) NOT NULL,
    initial_sl_price DECIMAL(30,12) NULL,
    current_sl_price DECIMAL(30,12) NOT NULL,
    tp1_price DECIMAL(30,12) NOT NULL,
    tp2_price DECIMAL(30,12) NOT NULL,
    tp3_price DECIMAL(30,12) NOT NULL,
    break_even_price DECIMAL(30,12) NULL,
    tp1_reached TINYINT(1) NOT NULL DEFAULT 0,
    tp2_reached TINYINT(1) NOT NULL DEFAULT 0,
    tp3_reached TINYINT(1) NOT NULL DEFAULT 0,
    sl_moved_to_be TINYINT(1) NOT NULL DEFAULT 0,
    sl_moved_to_tp1 TINYINT(1) NOT NULL DEFAULT 0,
    sl_stage ENUM('INITIAL','BE','TP1','FINAL') NOT NULL DEFAULT 'INITIAL',
    status VARCHAR(32) NOT NULL,
    close_reason VARCHAR(255) NULL,
    error_message TEXT NULL,
    opened_at TIMESTAMP NULL DEFAULT NULL,
    closed_at TIMESTAMP NULL DEFAULT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    external_id VARCHAR(64) NOT NULL,
    stop_plan_order_id VARCHAR(64) NULL,
    contract_symbol VARCHAR(32) NOT NULL,
    original_sl_price DECIMAL(30,12) NOT NULL,
    margin DECIMAL(30,12) NOT NULL,
    contract_size DECIMAL(30,12) NULL,
    fee_rate DECIMAL(20,12) NOT NULL DEFAULT 0,
    last_roi DECIMAL(20,8) NULL,
    break_even_moved_at DATETIME NULL,
    tp1_reached_at DATETIME NULL,
    tp2_reached_at DATETIME NULL,
    raw_open_response JSON NULL,
    raw_close_response JSON NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_trades_external_id (external_id),
    KEY idx_signal_id (signal_id),
    KEY idx_symbol (symbol),
    KEY idx_status (status),
    KEY idx_sl_stage (sl_stage),
    KEY idx_bingx_position_id (bingx_position_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
